In [19]:
from selenium import webdriver
import time
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
import time
import csv

## Live News Collection

In [45]:
# initializing chrome web driver
driver = webdriver.Chrome(executable_path='chromedriver_win32/chromedriver.exe')

dummy=input("Input currency forex pair")
currency=dummy

searchList=['Politics','Congress','GDP','CPI','Gold+price','Employment','Parliament','Banks','Democrat','Bear+Market','Bull+run','NATO','G7','War','G20','Silicon+valley','Natural+gas+Price','White+House','Stock+market','Capital+market','Inflation','Oil+prices','Natural+Calamities','BJP','B20','Stress+testing']
searchList.insert(0, currency)

data=[]
for i in searchList:
    
    resp=driver.get('https://www.google.com/search?q='+i+'&authuser=0&tbm=nws&sxsrf=APwXEddvFjyX-E3Jv6SMNq5CWpM-X9jFSg:1681868177846&ei=kUU_ZJOXM8_cptQPkoOQmA8&start=20&sa=N&ved=2ahUKEwjTo7Ka57T-AhVProkEHZIBBPM4ChDy0wN6BAgFEAc&biw=1036&bih=909&dpr=1.02')

    dv = driver.find_elements("xpath", '//div[@class="SoaBEf"]')
    for element in dv:
        title= element.find_element("xpath", './/div[@class="mCBkyc ynAwRc MBeuO nDgy9d"]')
        link = element.find_element("xpath", './/div/a')
        des = element.find_element("xpath", './/div[@class="GI74Re nDgy9d"]')
        date = element.find_element("xpath", './/div[@class="OSrXXb ZE0LJd YsWzw"]')
        publisher=element.find_element("xpath", './/div[@class="CEMjEf NUnG9d"]')

        data.append([title.text, link.get_attribute('href'), des.text, date.text, publisher.text])

driver.close()

df=pd.DataFrame(data, columns=['Titles', 'Links', 'Details', 'Date', 'Publisher'])
# print(df.head())
df.to_csv('GoogleNews.csv')

C:\Users\varsh\AppData\Local\Temp/ipykernel_4904/2582194017.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='chromedriver_win32/chromedriver.exe')

Input currency forex pair USDINR

In [46]:
import pandas as pd
# Save data as DataFrame
df = pd.DataFrame(data, columns=['Title', 'Link', 'Description', 'Date', 'Publisher'])
df.head()

,Title,Link,Description,Date,Publisher
0,BSE : Change in strike price interval and mini...,https://www.marketscreener.com/quote/stock/BSE...,NOTICES Notice No. 20230208-3 Notice Date ... ...,"Feb 8, 2023",Market Screener
1,USD/INR: Speculative Havoc for Day Traders Pos...,https://www.dailyforex.com/forex-technical-ana...,The USD/INR has seen whipsaw results on the la...,"Feb 1, 2023",DailyForex
2,SocGen recommends fading rally in USD/INR offs...,https://www.reuters.com/markets/currencies/soc...,Societe General expects the spread between the...,"Oct 21, 2022",Reuters
3,USD/INR Price Forecast – Traders Stay Cautious...,https://www.fxempire.com/forecasts/article/usd...,Traders are waiting for the U.S. inflation dat...,"Feb 13, 2023",FX Empire
4,USD/INR: Nervousness Proven Correct as Higher ...,https://www.dailyforex.com/forex-technical-ana...,The USD/INR is trading slightly below apex val...,"Feb 15, 2023",DailyForex

In [66]:
df1=df

In [67]:
from datetime import date, datetime
today = datetime.today().strftime('%Y-%m-%d')

In [68]:
import pandas as pd
import datetime as dt

df1['Date'] = df1['Date'].apply(lambda x: dt.datetime.today().strftime('%Y-%m-%d') if 'hour' in x or 'min' in x else (dt.datetime.today() - dt.timedelta(days=1)).strftime('%Y-%m-%d') if 'day ago' in x else (dt.datetime.today() - dt.timedelta(days=2)).strftime('%Y-%m-%d') if '2 days ago' in x else (dt.datetime.today() - dt.timedelta(days=3)).strftime('%Y-%m-%d') if '3 days ago' in x else (dt.datetime.today() - dt.timedelta(days=4)).strftime('%Y-%m-%d') if '4 days ago' in x else (dt.datetime.today() - dt.timedelta(days=5)).strftime('%Y-%m-%d') if '5 days ago' in x else (dt.datetime.today() - dt.timedelta(days=6)).strftime('%Y-%m-%d') if '6 days ago' in x else (dt.datetime.today() - dt.timedelta(days=7)).strftime('%Y-%m-%d') if '1 week ago' in x else x)
df1 = df1[~df1['Date'].str.contains('2022')]
df1 = df1[~df1['Date'].str.contains('weeks ago')]
df1 = df1[~df1['Date'].str.contains('month ago')]

In [69]:
df1 = df1.reset_index(drop=True)

In [70]:
df1 = df1[df1['Date'].str.contains('\d{4}-\d{2}-\d{2}')] # keep rows with date in YYYY-MM-DD format
df1['Date'].unique()

array(['2023-04-12', '2023-04-19', '2023-04-17', '2023-04-18',
       '2023-04-15', '2023-04-14', '2023-04-16', '2023-04-13'],
      dtype=object)

In [71]:
# assuming df1 is your dataframe,converting the 'Date' column from string to datetime format
df1['Date'] = pd.to_datetime(df1['Date'], infer_datetime_format=True)

In [72]:
df1

,Title,Link,Description,Date,Publisher
4,Buy USDINR; target of : 82.20 : ICICI Direct,https://www.moneycontrol.com/news/business/sto...,ICICI Direct's currency report on USDINR. The ...,2023-04-12,Moneycontrol
7,'Slap in the face': Freeland's Disney Plus com...,https://www.ctvnews.ca/politics/slap-in-the-fa...,"Once upon a time, Chrystia Freeland attempted ...",2023-04-19,CTV News
8,NDP aims at Doug Ford with pitch to toughen co...,https://www.thestar.com/politics/provincial/20...,Taking aim at conflict of interest concerns af...,2023-04-19,The Toronto Star
9,Doug Ford unveils plan to move Science Centre ...,https://www.thestar.com/politics/provincial/20...,A smaller Ontario Science Centre will be reloc...,2023-04-19,The Toronto Star
10,Justin Trudeau's luxury holiday scandal shows ...,https://www.thestar.com/politics/federal/2023/...,The Conservative leader and NDP Leader Jagmeet...,2023-04-19,The Toronto Star
...,...,...,...,...,...
207,Karnataka in Shock: BJP youth leader Praveen K...,https://m.timesofindia.com/videos/toi-original...,A shocking incident occurred in Kottur village...,2023-04-19,Times of India
208,Punjab BJP leader Balwinder Gill shot at by un...,https://www.tribuneindia.com/news/amritsar/pun...,"Punjab BJP SC morcha general secretary, Balwin...",2023-04-17,Tribune India
209,Missing from BJP’s Karnataka star campaigner l...,https://theprint.in/politics/missing-from-bjps...,BJP star campaigner list for Karnataka include...,2023-04-19,ThePrint
210,Karnataka election 2023 | Is BJP losing ground...,https://www.cnbctv18.com/politics/karnataka-el...,The recent rebellion within the Bharatiya Jana...,2023-04-18,CNBCTV18.com
211,"'Don't care', says Mamata Banerjee as Mukul Ro...",https://www.indiatvnews.com/news/india/tmc-mla...,TMC MLA Mukul Roy on Wednesday claimed his sup...,2023-04-19,India TV News

In [73]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
!pip install langid
import langid

Requirement already satisfied: langid in c:\users\varsh\anaconda3\lib\site-packages (1.1.6)
Requirement already satisfied: numpy in c:\users\varsh\anaconda3\lib\site-packages (from langid) (1.24.2)

[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
df1.columns

Index(['Title', 'Link', 'Description', 'Date', 'Publisher'], dtype='object')

In [75]:
# Download the Vader lexicon and langid model
nltk.download('vader_lexicon')
langid.set_languages(['en', 'hi', 'fr', 'de', 'es', 'it', 'ja', 'ko', 'nl', 'pt', 'ru', 'zh', 'ar'])

# Filter out non-English titles using langid
df1['lang'] = df1['Title'].apply(lambda x: langid.classify(x)[0])
df1 = df1[df1['lang'] == 'en']

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\varsh\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [76]:
# Extract the 'Title' column and convert it to a list
titles = df1['Title'].tolist()

# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Create an empty list to hold the sentiment scores
sentiment_scores = []
polarity=[]

# Perform sentiment analysis on each title
for title in titles:
    # Analyze the sentiment of the title using Vader lexicon
    sentiment = analyzer.polarity_scores(title)
    
    #adding compound score 
    sentiment_scores.append(sentiment['compound'])
    
    # Determine the sentiment label based on the compound score
    if sentiment['compound'] > 0:
        sentiment_label = 'positive'
    elif sentiment['compound'] < 0:
        sentiment_label = 'negative'
    else:
        sentiment_label = 'neutral'
    
    # Append the sentiment label to the list
    polarity.append(sentiment_label)

# Add the sentiment scores to the dataframe as a new column
df1['Sentiment_Score'] = sentiment_scores
df1['Polarity'] = polarity

# Output the modified dataframe to a new CSV file
df1.drop(['Link', 'Description', 'Publisher', 'lang'], axis=1, inplace=True)
df1.to_csv('sentiment_scores.csv', index=False)

C:\Users\varsh\AppData\Local\Temp/ipykernel_4904/86854237.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Sentiment_Score'] = sentiment_scores
C:\Users\varsh\AppData\Local\Temp/ipykernel_4904/86854237.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Polarity'] = polarity
C:\Users\varsh\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

# Multiple news per day, sorted datewise

In [77]:
df1=df1.sort_values('Date')
df1

,Title,Date,Sentiment_Score,Polarity
4,Buy USDINR; target of : 82.20 : ICICI Direct,2023-04-12,0.0000,neutral
108,Topic: NATO Mission Iraq,2023-04-12,0.0000,neutral
112,Topic: Transparency and accountability,2023-04-12,0.0000,neutral
72,Royal Bank financed $42B worth of fossil fuel ...,2023-04-13,0.2263,positive
154,Natural Gas Futures Trim Losses as First Stora...,2023-04-13,0.1779,positive
...,...,...,...,...
83,"Biden digs in with Democrats on debt limit, ca...",2023-04-19,-0.3612,negative
84,GOP blocks Democratic effort to replace Feinst...,2023-04-19,-0.2263,negative
85,Khanna headed to New Hampshire for premier Dem...,2023-04-19,0.0000,neutral
78,Morning Bid: Central banks on pause patrol,2023-04-19,0.0000,neutral
211,"'Don't care', says Mamata Banerjee as Mukul Ro...",2023-04-19,0.3818,positive

# Single news per day, based on first found

In [78]:
single_news = df1.groupby('Date').first().reset_index()[['Title', 'Date', 'Sentiment_Score', 'Polarity']].sort_values('Date')
single_news

,Title,Date,Sentiment_Score,Polarity
0,Buy USDINR; target of : 82.20 : ICICI Direct,2023-04-12,0.0000,neutral
1,Royal Bank financed $42B worth of fossil fuel ...,2023-04-13,0.2263,positive
2,New program aimed at finding better employment...,2023-04-14,0.6705,positive
3,The End of Faking It in Silicon Valley,2023-04-15,-0.4215,negative
4,US savers get savvy ditching and switching banks,2023-04-16,0.0000,neutral
5,Canada's main inflation indicator will plunge ...,2023-04-17,0.4588,positive
6,‘Staggering’ $300 Billion Prediction Reveals P...,2023-04-18,0.3182,positive
7,Seized assets from Silicon Valley Bank and Sig...,2023-04-19,0.1779,positive

# calculating aggregate sentiment per day

In [84]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from datetime import datetime

analyzer = SentimentIntensityAnalyzer()


# Calculate sentiment score for each date
grouped = df1.groupby('Date')

sentiment_by_date = grouped.agg({'Title': 'count', 'Sentiment_Score': 'mean'})

sentiment_by_date.drop(['Title'], axis=1, inplace=True)
sentiment_by_date

            Sentiment_Score
Date
2023-04-12         0.000000
2023-04-13         0.202100
2023-04-14         0.526150
2023-04-15         0.144236
2023-04-16        -0.054367
2023-04-17        -0.037571
2023-04-18        -0.039592
2023-04-19        -0.030058